<?php 
$annonces = array(
	1 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'caravane de roumain ',
 		'Body' => 'Vends caravane di roumain pas cher di tout sivouplé madamme',
 		'Date' => '26/05/1998',
		'Image' => 'image',
		'Nom' => 'vladislav',
		'Prenom' => 'Neculai',
		'Email' => 'nicoulesko@hotmail.com',
		'Numero' => '0626568975',
		'Adresse' => 'a coté di préhérique nord 69100',
),
	2 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'compuing careche luxche',
 		'Body' => 'compuing careche constrouiche avec biton armiche plombriche bounne état tres pouche roulé 5 allez retourche o portougal',
 		'Date' => '05/12/2015',
		'Image' => 'image',
		'Nom' => 'Da costa',
		'Prenom' => 'javier',
		'Email' => 'dacosta@gmail.com',
		'Numero' => '0712458965',
		'Adresse' => '80 rue des palaches 69800',
),

	3 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'coumping car mersoudes importé alloumagne ',
 		'Body' => 'vonds mersoudes campouing car avec broche kebab pour barbecue carburant salade tomates ogoins',
 		'Date' => '12/09/2015',
		'Image' => 'image',
		'Nom' => 'kulum',
		'Prenom' => 'zazam',
		'Email' => 'zazam@gmail.com',
		'Numero' => '0652545859',
		'Adresse' => '215 rue des louves 69100',
),
	4 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'vent rinoult 64 camping car sans ct',
 		'Body' => 'vent rinoult 64 iquipé cassette vhs panoupli cheb mami outilisé soulement pour allez o bled 8000€ firme ',
 		'Date' => '23/06/2015',
		'Image' => 'image',
		'Nom' => 'abde',
		'Prenom' => 'moha',
		'Email' => 'm.69@gmail.com',
		'Numero' => '0478754869',
		'Adresse' => '23 mas de la licorne 69100',
),
	5 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'campwing cawar ',
 		'Body' => 'campwing car pas cher paiement par western union ',
 		'Date' => '25/02/2006',
		'Image' => 'image',
		'Nom' => 'diaby',
		'Prenom' => 'souleimane',
		'Email' => 'soul@gmail.com',
		'Numero' => '002121489857595',
		'Adresse' => '25 avenue général soeur dakar',
),
	6 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	7 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	8 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),		
	9 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',		

),
	10 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',	
),	
);




?>