<?php 
$annonces = array(
	1 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	2 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),

	3 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	4 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	5 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	6 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	7 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),
	8 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',
),		
	9 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',		

),
	10 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Date' => 'date',
		'Image' => 'image',
		'Nom' => 'nom',
		'Prenom' => 'prenom',
		'Email' => 'email',
		'Numero' => 'numero',
		'Adresse' => 'adresse',	
),	
);




?>