<?php 
$temoignages = array(

	1 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	2 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	3 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	4 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	5 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	6 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	7 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	8 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	9 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),
	10 => array( 
 		'ID' => 'identifiant',
 		'Titre' => 'titre',
 		'Body' => 'body',
 		'Nom' => 'nom',
 		'Prenom' => 'prenom',
 		'Date' => 'date',
		'Email' => 'email',
),	

);

?>